version: 'latest'

services:
  db:
    image: nouchka/sqlite3:latest
    environment:
      - SQLITE3_DB=db.sqlite3
  django:
     image: raavi13/docker_1:${BUILD_NUMBER} 
     build:
       context: .
       dockerfile: Dockerfile       
     volumes:
       - .:/code 
     ports:
       -  "8000:8000"
     depends_on:
       - db
     env_file:
       - .env
  
 
