version: 'latest'

services:
  db:
    image: nouchka/sqlite3:latest
    environment:
      - SQLITE3_DB=db.sqlite3
  django:
     image: django-docker:0.0.1
     build:
       context: .
       dockerfile: Dockerfile       
     image: raavi13/docker_1:${BUILD_NUMBER} 
     volumes:
       - .:/code 
     ports:
       -  "8000:8000"
     depends_on:
       - db
  
 
