# Generated by Django 4.1.5 on 2023-03-16 16:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kapde', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime(2023, 3, 16, 22, 21, 39, 352603))),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kapde.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kapde.product')),
            ],
        ),
    ]
