# Generated by Django 5.0.2 on 2024-02-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapde', '0012_product_stock_alter_order_date_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
